language: cpp
dist: trusty
compiler:
  - clang++
  - gcc
os: linux
# Enable containerization support
sudo: false

env:
  global:
    # CODACY_PROJECT_TOKEN
    - secure: "addWK7CeZuhXrL19EeWIOuoKsC0nPs17TIRBu2AkfwZfdGFTBf8dGW/8KM7Vec/LhoflQr5cQX9GiIcwlxU8+mMpIFWvLjvE06dLo6yZiGTDHX7QrCYC096TRVbAEPCF88kGZ6Udw4FCvXbDNXJKgnAnSDkL/Mzb6cJ/FW1gylrtCNxKRwAy/0Ch2uR4jOKgHVZ18HdbqPBP1Awqe8whX43AKoHrQEweykMAsvhAD1M2MCoz5BwYQqI8XMmNq87ZjwVUOCY/JLfZVbfe+drMVD+7MLLLsVAytgjghG/oAGhUipIsQz+oJQR2NmPyTW5rfZq4tJgD7YaZUfuBCvMlin6AUeyyPxdkQ2UKttPOUbzH2qjltcpG96N46RRxeHR62z3eZ2aYKEXYmFulDCGHBUKyCJhYtjDVLQjMDEUXqvjuV9jqfScHPtZnYMbXrClkFtT3UsvU+1qkJ3fmrLE7jLgdgYu1bB6Gb3WGSwMmkS6M3Ayegv529wm9HF53kZ8eQb7kE5vuayJuPknED1wDsg3RfDYWw7X0Xvtd8kYXlnZ60BqdWczM/dY2h4XRD/sHiFsXsuDbXryjWMGRdtiQ39EzqUnxh0ANSjSB/XxnMzVB/QbTej5T190Pd8xKu+BDquYprQXYTf5brOU7M0FX+XQKWJCd/F8/7wW7+chWR6U="

#branches:
#  only:
#  - master
#  - develop

addons:
  apt:
    sources:
      # google test
      - ubuntu-toolchain-r-test
    packages:
    - libgtest-dev
    - gcovr
    - jq

before_install:
  # Install latest codacy-coverage-reporter using jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
  # Additional build agent information
  - cmake --version
  - gcovr --version
  # Check google-test installation
  - ls /usr/include/gtest
  - ls /usr/share/doc/libgtest-dev/
  - ls /usr/src/gtest/

script:
  - mkdir build
  # CMake
  - cd build && cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  # Build project
  - cd build && make
  # Run tests
  - cd build && make test
  # Collect coverage
  #- cd build && gcovr src/

after_success:
  # Send coverage report to codacy
  #- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - echo "Great Success!"